export const ID_GENERATOR = Symbol('ID_GENERATOR');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const AUTH_TOKEN_SERVICE = Symbol('AUTH_TOKEN_SERVICE');

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AUTHENTICATION_REPOSITORY = Symbol('AUTHENTICATION_REPOSITORY');
export const THREAD_REPOSITORY = Symbol('THREAD_REPOSITORY');
export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
export const COMMENT_LIKE_REPOSITORY = Symbol('COMMENT_LIKE_REPOSITORY');
export const REPLY_REPOSITORY = Symbol('REPLY_REPOSITORY');

export const THREAD_DETAILS_QUERY_SERVICE = Symbol(
  'THREAD_DETAILS_QUERY_SERVICE',
);
